Appiko: SDK EEPROM Management
SDK EEPROM Management
SDK-EVAL NUCLEO
Management of Software Development Kit eval board EEPROM.
Modules
SPI_Private_Functions
Functions
void EepromSpiInitialization (void)
Initializes the SPI for the EEPROM. SPI, MISO, MOSI and SCLK are the same used for the SPIRIT1. This function can be replaced by EepromCsPinInitialization if SpiritSpiInit is called.
void EepromCsPinInitialization (void)
Initialization of the CSn pin of the EEPROM. This function is called internally by EepromCsPinInitialization.
void EepromCsXnucleoPinInitialization (void)
Initialization of the CSn pin of the EEPROM for XNUCLEO boards.
uint8_t EepromStatus (void)
Read the status register.
void EepromRead (uint16_t nAddress, uint8_t cNbBytes, uint8_t *pcBuffer)
Read a page of the EEPROM. A page size is 32 bytes. The pages are 256. Page 0 address: 0x0000 Page 1 address: 0x0020 ... Page 255 address: 0x1FE0.
void EepromWrite (uint16_t nAddress, uint8_t cNbBytes, uint8_t *pcBuffer)
Write a page of the EEPROM. A page size is 32 bytes. The pages are 256. Page 0 address: 0x0000 Page 1 address: 0x0020 ... Page 255 address: 0x1FE0 It is allowed to write only a page for each operation. If the bytes exceed the single page location, the other bytes are written at the beginning.
uint8_t EepromResetSrwd (void)
Reset the ERSR status bit.
uint8_t EepromSetSrwd (void)
Set the ERSR status bit.
void EepromWriteEnable (void)
Set the internal WEL flag to allow write operation.
uint8_t SdkEvalGetHasEeprom (void)
This function is to query if EEPROM is present or not.
void SdkEvalSetHasEeprom (uint8_t eeprom)
This function is to set if EEPROM is present or not.
Detailed Description
See the file SDK_EVAL_EEPROM.h for more details.
Function Documentation
EepromCsPinInitialization()
void EepromCsPinInitialization (void)
Parameters
None
Return values
None
Definition at line 173 of file SDK_EVAL_EEPROM.c.
EepromCsXnucleoPinInitialization()
void EepromCsXnucleoPinInitialization (void)
Parameters
None
Return values
None
It affects EepromSPICSHigh/Low functions
Configure SPI pin: CS
Definition at line 201 of file SDK_EVAL_EEPROM.c.
Referenced by EepromIdentification().
EepromRead()
void EepromRead (uint16_t nAddress, uint8_t cNbBytes, uint8_t * pcBuffer)
Parameters
None
Return values
None
Definition at line 376 of file SDK_EVAL_EEPROM.c.
EepromResetSrwd()
uint8_t EepromResetSrwd (void)
Parameters
None
Return values
Status
Definition at line 324 of file SDK_EVAL_EEPROM.c.
EepromSetSrwd()
uint8_t EepromSetSrwd (void)
Parameters
None
Return values
Status
Definition at line 301 of file SDK_EVAL_EEPROM.c.
EepromSpiInitialization()
void EepromSpiInitialization (void)
Parameters
None
Return values
None
Definition at line 76 of file SDK_EVAL_EEPROM.c.
Referenced by EepromIdentification().
EepromStatus()
uint8_t EepromStatus (void)
Parameters
None
Return values
Status
Definition at line 278 of file SDK_EVAL_EEPROM.c.
Referenced by EepromIdentification().
EepromWrite()
void EepromWrite (uint16_t nAddress, uint8_t cNbBytes, uint8_t * pcBuffer)
Parameters
None
Return values
None
Definition at line 418 of file SDK_EVAL_EEPROM.c.
EepromWriteEnable()
void EepromWriteEnable (void)
Parameters
None
Return values
None
Definition at line 349 of file SDK_EVAL_EEPROM.c.
SdkEvalGetHasEeprom()
uint8_t SdkEvalGetHasEeprom (void)
Parameters
None
Return values
1 (yes) or 0 (no).
Definition at line 454 of file SDK_EVAL_EEPROM.c.
SdkEvalSetHasEeprom()
void SdkEvalSetHasEeprom (uint8_t eeprom)
Parameters
1 (yes) or 0 (no).
Return values
None
Definition at line 465 of file SDK_EVAL_EEPROM.c.