Appiko: Output pattern generator
Output pattern generator
Codebase » Peripheral Modules
Output pattern generator module is used for generating a one time digital signal pattern on a number of pins.
Data Structures
struct out_gen_config_t
Configuration structure for output pattern generation.
Macros
#define OUT_GEN_MAX_TRANSITIONS 64
#define OUT_GEN_MAX_NUM_OUT 4
Functions
void out_gen_init (uint32_t num_out, uint32_t *out_pins, bool *out_init_value)
Initialize the output pattern generator module with the information of the pins on which the pattern is generated.
void out_gen_start (out_gen_config_t *out_gen_config)
Start the generation of the pattern with the information provided.
void out_gen_stop (bool *out_vals)
Stop the output pattern generation and sets the output pins as specified in the arguments.
bool out_gen_is_on (void)
To know if the output pattern generator module is on.
uint32_t out_gen_get_ticks (void)
Function to get ticks since last call of out_gen_start.
Detailed Description
Macro Definition Documentation
OUT_GEN_MAX_NUM_OUT
#define OUT_GEN_MAX_NUM_OUT 4
The maximum number of output pins for which pattern can be generated
Definition at line 49 of file out_pattern_gen.h.
OUT_GEN_MAX_TRANSITIONS
#define OUT_GEN_MAX_TRANSITIONS 64
The maximum number of transitions that can occur in the generated pattern
Definition at line 46 of file out_pattern_gen.h.
Function Documentation
out_gen_get_ticks()
uint32_t out_gen_get_ticks (void) inline
Returns
Number of ms_timer ticks since last call of out_gen_start
Definition at line 132 of file out_pattern_gen.c.
References ms_timer_get_current_count().
out_gen_init()
void out_gen_init (uint32_t num_out, uint32_t * out_pins, bool * out_init_value)
Parameters
num_out The number of pins with pattern generation
out_pins Pointer to array with the pin numbers
out_init_value Pointer to an array containing the initial pin values
Definition at line 74 of file out_pattern_gen.c.
References ASSERT, and OUT_GEN_MAX_NUM_OUT.
Referenced by cam_trigger_init().
out_gen_is_on()
bool out_gen_is_on (void)
Returns
True if pattern generation is on and false if off
Definition at line 127 of file out_pattern_gen.c.
out_gen_start()
void out_gen_start (out_gen_config_t * out_gen_config)
Parameters
out_gen_config A pointer to configuration which is used to generate pattern.
Definition at line 89 of file out_pattern_gen.c.
References ASSERT, out_gen_config_t::next_out, out_gen_config_t::num_transitions, OUT_GEN_MAX_TRANSITIONS, and out_gen_config_t::transitions_durations.
out_gen_stop()
void out_gen_stop (bool * out_vals)
Parameters
out_vals Pointer to an array of digital values for the pins to be set to on stopping the pattern generation.
Definition at line 117 of file out_pattern_gen.c.
References ms_timer_stop().
Referenced by sensepi_cam_trigger_stop().