Appiko: Module that manages the LED UI
Module that manages the LED UI
Codebase » Peripheral Modules
This module is responsible for managing the LED UI by playing and stopping the different UI sequences a single time or in a loop. This module gets the LED sequences from the led_seq module and plays through the hal_pwm module.
Enumerations
enum led_ui_priority_t { LED_UI_LOW_PRIORITY = 0, LED_UI_MID_PRIORITY = 1, LED_UI_HIGH_PRIORITY = 2 }
The LED sequence priority levels.
enum led_ui_seq_t { , LED_UI_SINGLE_SEQ, LED_UI_SEQ_T_SIZE }
To specify if a sequence is run once or repeatedly.
Functions
void led_ui_single_start (led_sequences seq, led_ui_priority_t priority, bool reset)
Start a sequence to play once.
void led_ui_loop_start (led_sequences seq, led_ui_priority_t priority)
Start a sequence to play repeatedly.
void led_ui_type_stop_all (led_ui_seq_t type)
Stop all sequence of a particular type.
void led_ui_stop_seq (led_ui_seq_t type, led_sequences seq)
Stops a particular sequence of a particular type.
void led_ui_stop_priority (led_ui_seq_t type, uint32_t priority)
Stops LED sequences of a particular type and of a priority level or less.
void led_ui_stop_everything (void)
Stops all LED sequences running.
led_sequences led_ui_get_current_seq (led_ui_seq_t type)
Get the currently active LED UI sequence.
Detailed Description
Enumeration Type Documentation
led_ui_priority_t
enum led_ui_priority_t
Enumerator
LED_UI_LOW_PRIORITY
LED_UI_LOW_PRIORITY.
LED_UI_MID_PRIORITY
LED_UI_MID_PRIORITY.
LED_UI_HIGH_PRIORITY
LED_UI_HIGH_PRIORITY.
Definition at line 40 of file led_ui.h.
led_ui_seq_t
enum led_ui_seq_t
Enumerator
LED_UI_SINGLE_SEQ
Run a sequence repeatedly.
LED_UI_SEQ_T_SIZE
Run a sequence only once.
Only used to get num of elements in enum
Definition at line 48 of file led_ui.h.
Function Documentation
led_ui_get_current_seq()
led_sequences led_ui_get_current_seq (led_ui_seq_t type)
Parameters
type The type of sequence to return
Returns
The sequence that is active of type
Definition at line 308 of file led_ui.c.
led_ui_loop_start()
void led_ui_loop_start (led_sequences seq, led_ui_priority_t priority)
Parameters
seq The sequence to start
priority The priority of the sequence
Definition at line 247 of file led_ui.c.
led_ui_single_start()
void led_ui_single_start (led_sequences seq, led_ui_priority_t priority, bool reset)
Parameters
seq The sequence to start
priority The priority of the sequence
reset When true restarts if the same sequence is already playing
Definition at line 236 of file led_ui.c.
References LED_UI_SINGLE_SEQ.
Referenced by sensebe_tx_rx_swicht_range().
led_ui_stop_priority()
void led_ui_stop_priority (led_ui_seq_t type, uint32_t priority)
Parameters
type The type to be stopped
priority The priority level or less to be stopped
Definition at line 292 of file led_ui.c.
led_ui_stop_seq()
void led_ui_stop_seq (led_ui_seq_t type, led_sequences seq)
Parameters
type The type to be stopped
seq The sequence to be stopped
Definition at line 283 of file led_ui.c.
led_ui_type_stop_all()
void led_ui_type_stop_all (led_ui_seq_t type)
Parameters
type The type to be stopped
Definition at line 275 of file led_ui.c.
Referenced by sensepi_cam_trigger_stop(), and state_change_handler().