Appiko: Header for hardware testing application
Header for hardware testing application
Applications » Hardware testing application for Sense Rev4 board
This file contains all the test funtion declarations.
Functions
uint32_t power_test (void)
This function is used to check power on the board If program execution starts properly, it means power source is connected.
uint32_t dc_dc_test (void)
This fucntion is used to check DC/DC converter. If DC/DC circuit is present at input supply, funtion will return value 1.
uint32_t led_test (void)
This fucntion is used to check on board LEDs. Operator has to be there to check if LEDs are blinking properly or not.
uint32_t crystal_test (void)
This fucntion is used to check on low frequency crystal. Without LF-XTAL we cannot use RTC. Therefore RTC is used to detect LF-XTAL.
uint32_t rc_test (void)
This fucntion is used to check output RC very low frequency filter. This function will actully check for any AC part present in offset voltage.
uint32_t freq_filter_test (void)
This fucntion is used to check output filter designed for f(max)=10Hz This test will detect if any other frequency is supplied to device other than 10 Hz.
uint32_t pot_test (void)
This fucntion is used to check MCP4012 pot. In this function we will check an ratio between two signals obtained by changing gain by changing pot values.
Detailed Description
Function Documentation
crystal_test()
uint32_t crystal_test (void)
Returns
Value for Crystal test flag
Definition at line 227 of file hw_testing_app.c.
References MS_SINGLE_CALL, MS_TIMER0, ms_timer_init(), ms_timer_start(), and profiler_timer_init().
dc_dc_test()
uint32_t dc_dc_test (void)
Returns
Value for DC/DC test flag
Definition at line 153 of file hw_testing_app.c.
freq_filter_test()
uint32_t freq_filter_test (void)
Returns
Value for Frequency filter test flag
Definition at line 297 of file hw_testing_app.c.
led_test()
uint32_t led_test (void)
Returns
Value for LED test flag
Definition at line 168 of file hw_testing_app.c.
pot_test()
uint32_t pot_test (void)
Returns
Value for POT test flag
Definition at line 338 of file hw_testing_app.c.
References mcp4012_set_value().
power_test()
uint32_t power_test (void)
Returns
Value for power test flag
Definition at line 144 of file hw_testing_app.c.
rc_test()
uint32_t rc_test (void)
Returns
Value for RC filter test flag
Definition at line 269 of file hw_testing_app.c.
References mcp4012_set_value(), PIR_AMP_OFFSET_PIN, profiler_timer_deinit(), profiler_timer_init(), read_time_us(), SIMPLE_ADC_GAIN1_5, and simple_adc_get_value().