Appiko: SDK SPIRIT Management Identification Functions
SDK SPIRIT Management Identification Functions
SPIRIT DK » SDK SPIRIT Management » SDK SPIRIT Management Functions
Functions
void S2LPRadioSetXtalFrequency (uint32_t lXtalFrequency)
Set the XTAL frequency.
void TIM3_IRQHandler (void)
This function handles TIM3 global interrupt.
void S2LPManagementEnableTcxo (void)
uint32_t S2LPManagementComputeXtalFrequency (void)
This function can be used to automatically measure the XTAL frequency making use of the Spirit clock output to pin and an STM32L timer in compare mode.
uint8_t EepromIdentification (void)
Read the status register.
Detailed Description
Function Documentation
EepromIdentification()
uint8_t EepromIdentification (void)
Parameters
None
Return values
Status
Definition at line 547 of file S2LP_SDK_Util.c.
References EepromCsXnucleoPinInitialization(), EepromSpiInitialization(), and EepromStatus().
S2LPManagementComputeXtalFrequency()
uint32_t S2LPManagementComputeXtalFrequency (void)
Parameters
None.
Return values
None.
Definition at line 147 of file S2LP_SDK_Util.c.
S2LPManagementEnableTcxo()
void S2LPManagementEnableTcxo (void)
@addgroup SDK_SPIRIT_MANAGEMENT_FUNCTIONS
Definition at line 86 of file S2LP_SDK_Util.c.
S2LPRadioSetXtalFrequency()
void S2LPRadioSetXtalFrequency (uint32_t lXtalFrequency)
Note
this function must be called before any Radio setting.
Parameters
uint32_t XTAL frequency.
Return values
void.
Definition at line 1162 of file S2LP_Radio.c.
TIM3_IRQHandler()
void TIM3_IRQHandler (void)
Parameters
None.
Return values
None.
Definition at line 75 of file S2LP_SDK_Util.c.