Appiko: SPI Exported Functions
SPI Exported Functions
S2LP Libraries » SPI Driver
Functions
void SdkEvalSpiInit (void)
Write single or multiple registers.
void SdkEvalSpiDeinit (void)
Deinitializes the SPI.
StatusBytes SdkEvalSpiWriteRegisters (uint8_t cRegAddress, uint8_t cNbBytes, uint8_t *pcBuffer)
Write single or multiple registers.
StatusBytes SdkEvalSpiReadRegisters (uint8_t cRegAddress, uint8_t cNbBytes, uint8_t *pcBuffer)
Read single or multiple registers.
StatusBytes SdkEvalSpiCommandStrobes (uint8_t cCommandCode)
Send a command.
StatusBytes SdkEvalSpiWriteFifo (uint8_t cNbBytes, uint8_t *pcBuffer)
Write data into TX FIFO.
StatusBytes SdkEvalSpiReadFifo (uint8_t cNbBytes, uint8_t *pcBuffer)
Read data from RX FIFO.
void SdkEvalEnterShutdown (void)
Puts at logic 1 the SDN pin.
void SdkEvalExitShutdown (void)
Put at logic 0 the SDN pin.
SFlagStatus SdkEvalCheckShutdown (void)
check the logic(0 or 1) at the SDN pin.
Detailed Description
Function Documentation
SdkEvalCheckShutdown()
SFlagStatus SdkEvalCheckShutdown (void)
Parameters
None.
Return values
FlagStatus.
Definition at line 365 of file SDK_EVAL_Gpio.c.
References M2S_GPIO_SDN, and SdkEvalGpioGetLevel().
SdkEvalEnterShutdown()
void SdkEvalEnterShutdown (void)
Parameters
None.
Return values
None.
Definition at line 339 of file SDK_EVAL_Gpio.c.
SdkEvalExitShutdown()
void SdkEvalExitShutdown (void)
Parameters
None.
Return values
None.
Definition at line 351 of file SDK_EVAL_Gpio.c.
SdkEvalSpiCommandStrobes()
StatusBytes SdkEvalSpiCommandStrobes (uint8_t cCommandCode)
Parameters
cCommandCode command code to be sent
Return values
Device status
Definition at line 363 of file SDK_EVAL_Spi_Driver.c.
References COMMAND_HEADER, hal_spim_is_busy(), and hal_spim_tx_rx().
SdkEvalSpiDeinit()
void SdkEvalSpiDeinit (void)
Parameters
None
Return values
None
Definition at line 141 of file SDK_EVAL_Spi_Driver.c.
References hal_spim_deinit().
SdkEvalSpiInit()
void SdkEvalSpiInit (void)
Parameters
baudrate_prescaler baudrate prescaler to be used Must be one of the SPI_BaudRate_Prescaler .
Return values
NoneInitializes the SPI.
Parameters
None
Return values
None
Definition at line 231 of file SDK_EVAL_Spi_Driver.c.
References hal_spim_init_t::csBar_pin.
SdkEvalSpiReadFifo()
StatusBytes SdkEvalSpiReadFifo (uint8_t cNbBytes, uint8_t * pcBuffer)
Parameters
cNbBytes number of bytes to read from RX FIFO
pcBuffer pointer to data read from RX FIFO
Return values
Device status
Definition at line 410 of file SDK_EVAL_Spi_Driver.c.
References hal_spim_is_busy(), hal_spim_tx_rx(), LINEAR_FIFO_ADDRESS, and READ_HEADER.
SdkEvalSpiReadRegisters()
StatusBytes SdkEvalSpiReadRegisters (uint8_t cRegAddress, uint8_t cNbBytes, uint8_t * pcBuffer)
Parameters
cRegAddress base register's address to be read
cNbBytes number of registers and bytes to be read
pcBuffer pointer to the buffer of registers' values read
Return values
Device status
Definition at line 341 of file SDK_EVAL_Spi_Driver.c.
References hal_spim_is_busy(), hal_spim_tx_rx(), and READ_HEADER.
SdkEvalSpiWriteFifo()
StatusBytes SdkEvalSpiWriteFifo (uint8_t cNbBytes, uint8_t * pcBuffer)
Parameters
cNbBytes number of bytes to be written into TX FIFO
pcBuffer pointer to data to write
Return values
Device status
Definition at line 385 of file SDK_EVAL_Spi_Driver.c.
References hal_spim_is_busy(), hal_spim_tx_rx(), LINEAR_FIFO_ADDRESS, and WRITE_HEADER.
SdkEvalSpiWriteRegisters()
StatusBytes SdkEvalSpiWriteRegisters (uint8_t cRegAddress, uint8_t cNbBytes, uint8_t * pcBuffer)
Parameters
cRegAddress base register's address to be write
cNbBytes number of registers and bytes to be write
pcBuffer pointer to the buffer of values have to be written into registers
Return values
Device status
Definition at line 314 of file SDK_EVAL_Spi_Driver.c.
References hal_spim_is_busy(), hal_spim_tx_rx(), and WRITE_HEADER.