var searchData=
[
  ['static_20and_20runtime_20assertion',['Static and runtime assertion',['../group__group__assertion.html',1,'']]],
  ['softdevice_20event_20handler',['Softdevice event handler',['../group__group__evt__sd__handler.html',1,'']]],
  ['saadc_20hal',['SAADC HAL',['../group__group__saadc.html',1,'']]],
  ['softdevice_20assist_20libraries',['SoftDevice Assist libraries',['../group__group__sd__assist.html',1,'']]],
  ['simple_20adc_20driver',['Simple ADC driver',['../group__group__simple__adc.html',1,'']]],
  ['simple_20pwm_20driver',['Simple PWM driver',['../group__group__simple__pwm.html',1,'']]],
  ['spi_20master_20hal',['SPI Master HAL',['../group__group__spim__driver.html',1,'']]],
  ['sdk_20spirit_20management_20identification_20functions',['SDK SPIRIT Management Identification Functions',['../group__IDENTIFICATION__FUNCTIONS.html',1,'']]],
  ['s2lp_20libraries',['S2LP Libraries',['../group__S2LP__Libraries.html',1,'']]],
  ['spi_20driver',['SPI Driver',['../group__S2LP__SPI__Driver.html',1,'']]],
  ['saadc_20logger',['SAADC Logger',['../group__saadc__logger.html',1,'']]],
  ['sdk_20basic_20generic',['SDK Basic Generic',['../group__SDK__Basic__Generic.html',1,'']]],
  ['sdk_20basic_20generic_20a',['SDK Basic Generic A',['../group__SDK__Basic__Generic__A.html',1,'']]],
  ['sdk_20basic_20generic_20b',['SDK Basic Generic B',['../group__SDK__Basic__Generic__B.html',1,'']]],
  ['sdk_20eeprom_20management',['SDK EEPROM Management',['../group__SDK__EEPROM.html',1,'']]],
  ['sdk_20eval_20button',['SDK EVAL Button',['../group__SDK__EVAL__Button.html',1,'']]],
  ['sdk_20eval_20button_20exported_20constants',['SDK EVAL Button Exported Constants',['../group__SDK__EVAL__Button__Exported__Constants.html',1,'']]],
  ['sdk_20eval_20button_20exported_20functions',['SDK EVAL Button Exported Functions',['../group__SDK__EVAL__Button__Exported__Functions.html',1,'']]],
  ['sdk_20eval_20button_20exported_20macros',['SDK EVAL Button Exported Macros',['../group__SDK__EVAL__Button__Exported__Macros.html',1,'']]],
  ['sdk_20eval_20button_20exported_20types',['SDK EVAL Button Exported Types',['../group__SDK__EVAL__Button__Exported__Types.html',1,'']]],
  ['sdk_20eval_20button_20private_20defines',['SDK EVAL Button Private Defines',['../group__SDK__EVAL__Button__Private__Defines.html',1,'']]],
  ['sdk_20eval_20button_20private_20function_20prototypes',['SDK EVAL Button Private Function Prototypes',['../group__SDK__EVAL__Button__Private__FunctionPrototypes.html',1,'']]],
  ['sdk_20eval_20button_20private_20functions',['SDK EVAL Button Private Functions',['../group__SDK__EVAL__Button__Private__Functions.html',1,'']]],
  ['sdk_20eval_20button_20private_20macros',['SDK EVAL Button Private Macros',['../group__SDK__EVAL__Button__Private__Macros.html',1,'']]],
  ['sdk_20eval_20button_20private_20types_20definitions',['SDK EVAL Button Private Types Definitions',['../group__SDK__EVAL__Button__Private__TypesDefinitions.html',1,'']]],
  ['sdk_20eval_20com',['SDK EVAL Com',['../group__SDK__EVAL__Com.html',1,'']]],
  ['sdk_20eval_20com_20exported_20functions',['SDK EVAL Com Exported Functions',['../group__SDK__EVAL__Com__Exported__Functions.html',1,'']]],
  ['sdk_20eval_20com_20exported_20types',['SDK EVAL Com Exported Types',['../group__SDK__EVAL__Com__Exported__Types.html',1,'']]],
  ['sdk_20eval_20com_20private_20defines',['SDK EVAL Com Private Defines',['../group__SDK__EVAL__Com__Private__Defines.html',1,'']]],
  ['sdk_20eval_20com_20private_20functions',['SDK EVAL Com Private Functions',['../group__SDK__EVAL__Com__Private__Functions.html',1,'']]],
  ['sdk_20eval_20com_20private_20macros',['SDK EVAL Com Private Macros',['../group__SDK__EVAL__Com__Private__Macros.html',1,'']]],
  ['sdk_20eval_20com_20private_20types_20definitions',['SDK EVAL Com Private Types Definitions',['../group__SDK__EVAL__Com__Private__TypesDefinitions.html',1,'']]],
  ['sdk_20eval_20com_20private_20variables',['SDK EVAL Com Private Variables',['../group__SDK__EVAL__Com__Private__Variables.html',1,'']]],
  ['sdk_20eval_20config',['SDK EVAL Config',['../group__SDK__EVAL__Config.html',1,'']]],
  ['sdk_20eval_20config_20exported_20constants',['SDK EVAL Config Exported Constants',['../group__SDK__EVAL__Config__Exported__Constants.html',1,'']]],
  ['sdk_20eval_20config_20exported_20functions',['SDK EVAL Config Exported Functions',['../group__SDK__EVAL__Config__Exported__Functions.html',1,'']]],
  ['sdk_20eval_20config_20private_20defines',['SDK EVAL Config Private Defines',['../group__SDK__EVAL__Config__Private__Defines.html',1,'']]],
  ['sdk_20eval_20config_20private_20function_20prototypes',['SDK EVAL Config Private Function Prototypes',['../group__SDK__EVAL__Config__Private__FunctionPrototypes.html',1,'']]],
  ['sdk_20eval_20config_20private_20functions',['SDK EVAL Config Private Functions',['../group__SDK__EVAL__Config__Private__Functions.html',1,'']]],
  ['sdk_20eval_20config_20private_20macros',['SDK EVAL Config Private Macros',['../group__SDK__EVAL__Config__Private__Macros.html',1,'']]],
  ['sdk_20eval_20config_20private_20types_20definitions',['SDK EVAL Config Private Types Definitions',['../group__SDK__EVAL__Config__Private__TypesDefinitions.html',1,'']]],
  ['sdk_20eval_20config_20private_20variables',['SDK EVAL Config Private Variables',['../group__SDK__EVAL__Config__Private__Variables.html',1,'']]],
  ['sdk_20eval_20gpio',['SDK EVAL Gpio',['../group__SDK__EVAL__Gpio.html',1,'']]],
  ['sdk_20eval_20gpio_20exported_20constants',['SDK EVAL Gpio Exported Constants',['../group__SDK__EVAL__Gpio__Exported__Constants.html',1,'']]],
  ['sdk_20eval_20gpio_20exported_20functions',['SDK EVAL Gpio Exported Functions',['../group__SDK__EVAL__Gpio__Exported__Functions.html',1,'']]],
  ['sdk_20eval_20gpio_20exported_20macros',['SDK EVAL Gpio Exported Macros',['../group__SDK__EVAL__Gpio__Exported__Macros.html',1,'']]],
  ['sdk_20eval_20gpio_20exported_20types',['SDK EVAL Gpio Exported Types',['../group__SDK__EVAL__Gpio__Exported__Types.html',1,'']]],
  ['sdk_20eval_20gpio_20private_20functions',['SDK EVAL Gpio Private Functions',['../group__SDK__EVAL__Gpio__Private__Functions.html',1,'']]],
  ['sdk_20eval_20gpio_20private_20variables',['SDK EVAL Gpio Private Variables',['../group__SDK__EVAL__Gpio__Private__Variables.html',1,'']]],
  ['sdk_20eval_20led',['SDK EVAL Led',['../group__SDK__EVAL__Led.html',1,'']]],
  ['sdk_20eval_20led_20exported_20constants',['SDK EVAL Led Exported Constants',['../group__SDK__EVAL__Led__Exported__Constants.html',1,'']]],
  ['sdk_20eval_20led_20exported_20functions',['SDK EVAL Led Exported Functions',['../group__SDK__EVAL__Led__Exported__Functions.html',1,'']]],
  ['sdk_20eval_20led_20exported_20macros',['SDK EVAL Led Exported Macros',['../group__SDK__EVAL__Led__Exported__Macros.html',1,'']]],
  ['sdk_20eval_20led_20exported_20types',['SDK EVAL Led Exported Types',['../group__SDK__EVAL__Led__Exported__Types.html',1,'']]],
  ['sdk_20eval_20led_20private_20defines',['SDK EVAL Led Private Defines',['../group__SDK__EVAL__Led__Private__Defines.html',1,'']]],
  ['sdk_20eval_20led_20private_20function_20prototypes',['SDK EVAL Led Private Function Prototypes',['../group__SDK__EVAL__Led__Private__FunctionPrototypes.html',1,'']]],
  ['sdk_20eval_20led_20private_20functions',['SDK EVAL Led Private Functions',['../group__SDK__EVAL__Led__Private__Functions.html',1,'']]],
  ['sdk_20eval_20led_20private_20macros',['SDK EVAL Led Private Macros',['../group__SDK__EVAL__Led__Private__Macros.html',1,'']]],
  ['sdk_20eval_20led_20private_20types_20definitions',['SDK EVAL Led Private Types Definitions',['../group__SDK__EVAL__Led__Private__TypesDefinitions.html',1,'']]],
  ['sdk_20eval_20led_20private_20variables',['SDK EVAL Led Private Variables',['../group__SDK__EVAL__Led__Private__Variables.html',1,'']]],
  ['sdk_2deval_20nucleo',['SDK-EVAL NUCLEO',['../group__SDK__EVAL__NUCLEO.html',1,'']]],
  ['sdk_20eval_20spi',['SDK EVAL Spi',['../group__SDK__EVAL__Spi.html',1,'']]],
  ['sdk_5feval_5fspi_5fperipheral_5fgpio',['SDK_EVAL_Spi_Peripheral_Gpio',['../group__SDK__EVAL__Spi__Peripheral__Gpio.html',1,'']]],
  ['sdk_20examples',['SDK Examples',['../group__SDK__Examples.html',1,'']]],
  ['sdk_20spirit_20management',['SDK SPIRIT Management',['../group__SDK__SPIRIT__MANAGEMENT.html',1,'']]],
  ['sdk_20spirit_20management_20functions',['SDK SPIRIT Management Functions',['../group__SDK__SPIRIT__MANAGEMENT__FUNCTIONS.html',1,'']]],
  ['spi_20exported_20constants',['SPI Exported Constants',['../group__SPI__Exported__Constants.html',1,'']]],
  ['spi_20exported_20functions',['SPI Exported Functions',['../group__SPI__Exported__Functions.html',1,'']]],
  ['spi_20exported_20macros',['SPI Exported Macros',['../group__SPI__Exported__Macros.html',1,'']]],
  ['spi_20exported_20types',['SPI Exported Types',['../group__SPI__Exported__Types.html',1,'']]],
  ['spi_5fheaders',['SPI_Headers',['../group__SPI__Headers.html',1,'']]],
  ['spi_5fprivate_5fdefines',['SPI_Private_Defines',['../group__SPI__Private__Defines.html',1,'']]],
  ['spi_5fprivate_5ffunctionprototypes',['SPI_Private_FunctionPrototypes',['../group__SPI__Private__FunctionPrototypes.html',1,'']]],
  ['spi_5fprivate_5ffunctions',['SPI_Private_Functions',['../group__SPI__Private__Functions.html',1,'']]],
  ['spi_5fprivate_5fmacros',['SPI_Private_Macros',['../group__SPI__Private__Macros.html',1,'']]],
  ['spi_5fprivate_5fvariables',['SPI_Private_Variables',['../group__SPI__Private__Variables.html',1,'']]],
  ['spirit_20dk',['SPIRIT DK',['../group__SPIRIT__DK.html',1,'']]],
  ['system_20level_20testing_20application_20for_20sense_20rev4_20board',['System level testing application for Sense Rev4 board',['../group__sys__lvl__testing.html',1,'']]]
];
